---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: file-upload
  namespace: spike-system
spec:
  replicas: 1
  template:
    metadata:
      name: file-upload
      labels:
        app: file-upload
        version: v1
    spec:
      containers:
      - name: file-upload
        image: eu.gcr.io/parcel-vision/file-upload:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: file-upload-config
        ports:
        - name: http-file-upload
          containerPort: 8888