# file-upload service
---
apiVersion: v1
kind: Service
metadata:
  name: file-upload
  labels:
    app: file-upload
spec:
  type: ClusterIP
  selector:
    app: file-upload
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: http-file-upload