---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: file-upload
spec:
  replicas: 1
  template:
    metadata:
      name: file-upload
      labels:
        app: file-upload
        version: v1
    spec:
      containers:
      - name: file-upload
        image: eu.gcr.io/parcel-vision/file-upload:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: file-upload-config
        ports:
          - containerPort: 8888
        volumeMounts:
          - name: nfs-pvc
            mountPath: "/mnt"
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfs